### ISSUE TITLE
Move all configuration files from classpath to docker directories

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#701] opened 2019-05-31 13:21 UTC
Currently, `reference.conf` configs, and some `application.conf` also live inside `.jar` files. This makes it pretty hard to introspect them in case of some misunderstanding in face of bugs or alike.

Moving them to docker's filesystem would make it easier to read actual configs used by our apps.

**Comment by alari** [comment] 2019-05-31 14:03
Looks like a duplicate of #464.

`reference.conf` files are very handy to have in corresponding modules, but we definitely should get rid of bundling `application.conf` anywhere -- it should be provided as a volume.

On another hand, `reference.conf` could be of use iff we call `ConfigFactory.load()` in the appropriate module, or assume that it's going to be called just like we expect it to be on the end of the world. This way, configuration becomes an obscure aspect of the program.

Let's not move conf files to docker directories. Let's aim to remove all config files from the source tree, and provide only `application.conf` files in docker volumes (one in node, another one in statemachine).

And reading the actual configs sounds like a different story to config files management, don't you think so?

**Closed** 2020-11-10 08:46 UTC
Labels: ~infrastructure, ~node, ~statemachine, ~virtual machine, ~worker
